# This workflow contains jobs for downloading player data
name: Player Data Downloader
on:
  workflow_dispatch:
    inputs:
      first_id:
        description: 'First Player ID'
        required: false
        default: 30000
      last_id:
        description: 'Last Player ID'
        required: false
        default: 30100
      threads:
        description: 'Number of Execution Threads'
        required: false
        default: 10

jobs:
  download:
    name: Download Player Data
    runs-on: ubuntu-latest
    # for local run --  $ act -j build -P ubuntu-latest=nektos/act-environments-ubuntu:18.04
    steps:
      # Clone repository with all branches and tags into github virtual machine
      - uses: actions/checkout@v2

      # Download and Install specific JDK version
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
         # for act caching download https://static.azul.com/zulu/bin/zulu11.43.21-ca-jdk11.0.9-linux_x64.tar.gz
         # to root workdir an uncomment
         # jdkFile: zulu11.43.21-ca-jdk11.0.9-linux_x64.tar.gz

      # Load packages from cache if present
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Build project, run tests and send to SonarCloud for analysis
      - name: Install KG Parser
        run: mvn install -Dmaven.javadoc.skip -Dmaven.test.skip=true

      # Set start time to variable
      - run: echo "::set-output name=start::$(date)"
        id: start_time
      # Run Player Data Downloader with inputs provided from dispatch if present
      # or run with defaults and save into data directory
      - name: Download Data
        # todo: pass paths to generated input file and output file
        run: java -Dlog4j.configurationFile=log4j2.xml -jar kgstatsSrv/target/kgstats-srv-1.0.jar DOWNLOAD_PLAYER_DATA data ${{ github.event.inputs.first_id }} ${{ github.event.inputs.last_id }} ${{ github.event.inputs.threads }}

      - run: echo "::set-output name=end::$(date)"
        id: end_time

      - name: Telegram Message Notify
        uses: appleboy/telegram-action@v0.1.0
        with:
          format: html
          to: ${{ secrets.TGBOT_CHAT }}
          token: ${{ secrets.TGBOT_TOKEN }}
          message: |
            <strong>GitHub Player Data Downloader (Manual Dispatch)</strong>
            <pre><code>
              Input Data:
                    First Player ID:  ${{ github.event.inputs.first_id }}
                     Last Player ID:  ${{ github.event.inputs.last_id }}
                  Execution Threads:  ${{ github.event.inputs.threads }}
              Time:
               Start: ${{steps.start_time.outputs.start}}
                 End: ${{steps.end_time.outputs.end}}
            </code></pre>

      # Archive all downloaded .json files
      - name: Archive Data
        run: tar cvzf "$(ls data).tar.gz" data/*

      # Configure AWS CLI with credentials from repository secrets
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # Upload Archived Data into Bucket
      - name: Copy Archived Data to S3
        run: aws s3 cp "$(ls data).tar.gz" s3://dievri-kgparser

      # Process downloaded files
      - name: Prepare MySQL database
        run: |
              sudo systemctl start mysql
              sudo mysql -uroot -proot -e "create database actions;"

      - name: Parse json files and import data to the database
        # todo: pass path to input file, it must be the file saved as output file by DOWNLOAD_PLAYER_DATA execution
        run: java -jar kgstatsSrv/target/kgstats-srv-1.0.jar -Dspring.profiles.active=database -Dspring.config.name=application.actions.properties -Dspring.config.location=kgstatsSrv/src/main/resources/ IMPORT_JSON_TO_DATABASE "data" ${{ github.event.inputs.first_id }} ${{ github.event.inputs.last_id }} 1 "$(ls data)"

      - name: Create Database Dump
        run: sudo mysqldump -uroot -proot actions > "$(ls data).sql"

      - name: Upload DB Dump to s3
        run: aws s3 cp "$(ls data).sql" s3://dievri-kgparser

      - name: Telegram Message Notify
        uses: appleboy/telegram-action@v0.1.0
        with:
          format: html
          to: ${{ secrets.TGBOT_CHAT }}
          token: ${{ secrets.TGBOT_TOKEN }}
          message: |
            <strong>GitHub Player Data Downloader (Manual Dispatch)</strong>
            <pre><code>
              archive with json files and database dump uploaded to s3
            </code></pre>
